(function () {
  const panel = document.querySelector('.brand-panel');
  if (!panel || !document.querySelector('[data-auth-form="login"]')) return;
  const translations = {
    en: { eyebrow: 'Oud Compass | Employees & Landlord portal', title: 'One secure portal for staff, departments, and landlords.', copy: 'Private, refined, and built for premium real-estate operations.', role: ['Role-based access', 'Every account is routed to the workspace built for its responsibilities.'], bilingual: ['Built for bilingual rollout', 'Switch between English and Arabic while keeping the same calm experience.'] },
    ar: { eyebrow: 'منصة بوصلة عود للموظفين وملاك العقارات', title: 'بوابة آمنة واحدة للموظفين والأقسام وملاك العقارات.', copy: 'بوابة خاصة وراقية مصممة لعمليات العقارات الفاخرة.', role: ['صلاحيات حسب الدور', 'يتم توجيه كل حساب إلى مساحة العمل المناسبة لمسؤولياته.'], bilingual: ['مصممة للاستخدام باللغتين', 'انتقل بين العربية والإنجليزية مع الحفاظ على تجربة هادئة ومتناسقة.'] }
  };
  const original = { eyebrow: panel.querySelector('.brand-copy .eyebrow'), title: panel.querySelector('.brand-copy h1'), copy: panel.querySelector('.brand-copy p:not(.eyebrow)'), features: panel.querySelectorAll('.feature'), demo: document.querySelector('.demo-credentials') };
  function apply() { const lang = localStorage.getItem('oud-lang') === 'ar' ? 'ar' : 'en'; const text = translations[lang]; original.eyebrow.textContent = text.eyebrow; original.title.textContent = text.title; original.copy.textContent = text.copy; original.features[0].querySelector('strong').textContent = text.role[0]; original.features[0].querySelector('span').textContent = text.role[1]; original.features[1].querySelector('strong').textContent = text.bilingual[0]; original.features[1].querySelector('span').textContent = text.bilingual[1]; if (original.demo && lang === 'ar') original.demo.innerHTML = '<strong>دخول تجريبي</strong><span class="demo-ready">✓ موظف · employee@oud.sa</span><span class="demo-pending">✕ مدير قسم · manager@oud.sa</span><span class="demo-ready">✓ مالك عقار · landlord@oud.sa</span><span class="demo-pending">✕ مسؤول النظام · admin@oud.sa</span><span>كلمة المرور · 1234</span>'; if (original.demo && lang === 'en') original.demo.innerHTML = '<strong>Demo access</strong><span class="demo-ready">✓ Employee · employee@oud.sa</span><span class="demo-pending">✕ Manager · manager@oud.sa</span><span class="demo-ready">✓ Landlord · landlord@oud.sa</span><span class="demo-pending">✕ Super Admin · admin@oud.sa</span><span>Password · 1234</span>'; }
  document.addEventListener('click', (event) => { if (event.target.closest('[data-lang]')) window.setTimeout(apply, 0); }); apply();
})();
