(function () {
  const page = document.body.dataset.landlordPage;
  const content = {
    properties: ['Properties', 'Your portfolio', 'Review the properties connected to your landlord account.', [['OUD Reserve', 'Mixed use · Riyadh · 54 units · 86% occupancy'], ['OUD Square', 'Mixed use · Riyadh · Portfolio access available']]],
    reports: ['Reports', 'Property reporting', 'Review monthly, quarterly, budget, maintenance, and market reports.', [['Monthly performance report', 'August 2026 · OUD Reserve · PDF'], ['Property budget review', 'Q3 2026 · OUD Reserve · PDF'], ['Maintenance summary', 'August 2026 · OUD Reserve · PDF'], ['Market positioning report', 'Q2 2026 · OUD Square · PDF'], ['Destination progress report', 'August 2026 · OUD Dunes · PDF'], ['Development update', 'August 2026 · La Perle by OUD · PDF']]],
    documents: ['Documents', 'Property library', 'Access contracts, invoices, certificates, and property records.', [['OUD Reserve lease register', 'PDF · Updated this month'], ['Property insurance certificate', 'PDF · Updated last month'], ['Tenant contract register', 'XLSX · Updated last month']]],
    approvals: ['Approvals', 'Action required', 'Review requests, supporting documents, and respond with a decision.', [['Lobby maintenance budget', 'OUD Reserve · Submitted 2 days ago'], ['Tenant fit-out request', 'OUD Reserve · Submitted 5 days ago'], ['Special event approval', 'OUD Square · Submitted 1 week ago'], ['Landscape maintenance renewal', 'OUD Dunes · Submitted 3 days ago'], ['Retail signage request', 'OUD Square · Submitted 6 days ago'], ['Construction milestone review', 'La Perle by OUD · Submitted 9 days ago']]]
  }[page];
  const nav = [['Dashboard', 'landlord_dashboard.html'], ['Properties', 'landlord_properties.html'], ['Reports', 'landlord_reports.html'], ['Documents', 'landlord_documents.html'], ['Approvals', 'landlord_approvals.html']];
  document.body.innerHTML = `<div class="portal landlord-portal"><aside class="sidebar"><div class="sidebar-brand"><a href="landlord_dashboard.html"><img src="https://images.squarespace-cdn.com/content/v1/68f677afba491e524acf3912/b583b255-3b47-4a75-94fb-1ae7328e235a/Full+Logo+-+New+light.png?format=1500w" alt="OUD Real Estate"></a></div><p class="nav-label">Property workspace</p><nav class="nav">${nav.map(([label, href]) => `<a class="${label.toLowerCase() === page ? 'active' : ''}" href="${href}">${label}</a>`).join('')}</nav></aside><main class="portal-main"><header class="topbar"><div class="topbar-title"><span>Oud Compass | Landlord portal</span><strong>${content[0]}</strong></div><div class="topbar-actions"><div class="portal-profile"><strong>Saeed ALKHATANI</strong><span>Landlord · landlord@oud.sa</span></div><a class="button button-secondary" href="user_login.html">Sign out</a></div></header><section class="content landlord-content"><section class="hero landlord-hero"><div><p class="eyebrow">${content[1]}</p><h1>${content[0]}.</h1><p>${content[2]}</p></div></section><section class="card ${page === 'approvals' ? 'approval-list' : 'report-list'}">${content[3].map((item) => { const href = page === 'approvals' ? `landlord_approval_detail.html?request=${encodeURIComponent(item[0])}` : page === 'reports' ? `landlord_report_detail.html?report=${encodeURIComponent(item[0])}` : '#'; return `<a href="${href}"><span><strong>${item[0]}</strong><small>${item[1]}</small></span><b class="row-action">${page === 'approvals' ? 'Review' : page === 'properties' ? 'View' : 'Download'}</b></a>`; }).join('')}</section></section></main></div>`;
  if (page === 'reports') document.querySelectorAll('.report-list > a').forEach((row) => { const view = document.createElement('button'); view.type = 'button'; view.className = 'report-view'; view.textContent = 'View'; view.onclick = () => { window.location.href = `landlord_report_detail.html?report=${encodeURIComponent(row.querySelector('strong').textContent)}`; }; row.append(view); });
  if (page === 'approvals') document.querySelectorAll('.approval-list > a').forEach((row) => {
    const request = encodeURIComponent(row.querySelector('strong').textContent);
    const review = row.querySelector('.row-action');
    review.className = 'approval-review';
    review.addEventListener('click', (event) => { event.preventDefault(); event.stopPropagation(); window.location.href = `landlord_approval_detail.html?request=${request}`; });
    const approve = document.createElement('button'); approve.type = 'button'; approve.className = 'approval-approve'; approve.textContent = 'Approve'; approve.onclick = () => { window.location.href = `landlord_approval_detail.html?request=${request}`; }; row.append(approve);
  });
})();
