(function () {
  const translations = {
    'Workspace': 'مساحة العمل', 'Dashboard': 'لوحة التحكم', 'Documents': 'المستندات', 'Oud Academy': 'أكاديمية عود', 'Announcements': 'الإعلانات', 'Search': 'البحث', 'Employee dashboard': 'لوحة الموظف', 'Sign out': 'تسجيل الخروج', 'Your workspace': 'مساحة العمل الخاصة بك', 'Welcome back.': 'مرحباً بعودتك.', 'Department': 'القسم', 'View-only access': 'صلاحية عرض فقط', 'Department files': 'ملفات القسم', 'Training items': 'مواد التدريب', 'Latest department updates': 'آخر تحديثات القسم', 'Profile status': 'حالة الملف الشخصي', 'Your access is active': 'صلاحيتك مفعلة', 'Documents': 'المستندات', 'Training': 'التدريب', 'Updates': 'التحديثات', 'Department library': 'مكتبة القسم', 'Oud Academy': 'أكاديمية عود', 'Announcements': 'الإعلانات', 'Recent activity': 'النشاط الأخير', 'View all': 'عرض الكل', 'Quick access': 'وصول سريع', 'Download latest document': 'تحميل أحدث مستند', 'Open training materials': 'فتح مواد التدريب', 'Search department content': 'البحث في محتوى القسم', 'Private library': 'مكتبة خاصة', 'Department documents.': 'مستندات القسم.', 'View and download documents shared with your department.': 'استعرض وحمّل المستندات المشتركة مع قسمك.', 'Operations': 'العمليات', 'Policies': 'السياسات', 'Templates': 'النماذج', 'Training library': 'مكتبة التدريب', 'Keep learning.': 'استمر في التعلم.', 'Access training files for your role, health, safety, and everyday operations.': 'ادخل إلى مواد التدريب الخاصة بدورك والصحة والسلامة والعمليات اليومية.', 'Required': 'إلزامي', 'Hospitality': 'الضيافة', 'Reference': 'مرجع', 'Department updates': 'تحديثات القسم', 'Stay informed.': 'ابقَ على اطلاع.', 'Messages and updates from your department manager and OUD Academy.': 'رسائل وتحديثات مدير القسم وأكاديمية عود.', 'Latest announcements': 'أحدث الإعلانات', 'Find content': 'ابحث عن المحتوى', 'Search your workspace.': 'ابحث في مساحة عملك.', 'Search across documents, training materials, and department announcements.': 'ابحث في المستندات ومواد التدريب وإعلانات القسم.', 'Search documents and announcements': 'البحث في المستندات والإعلانات', 'Open library →': 'فتح المكتبة ←', 'View training →': 'عرض التدريب ←', 'Read updates →': 'قراءة التحديثات ←', 'Open result →': 'فتح النتيجة ←', 'Download document →': 'تحميل المستند ←', 'Open training →': 'فتح التدريب ←', 'Download guide →': 'تحميل الدليل ←', 'Hospitality Management': 'إدارة الضيافة', 'Learning & development': 'التعلم والتطوير', 'Department library': 'مكتبة القسم', 'Today': 'اليوم', 'Yesterday': 'أمس', '3 days ago': 'منذ 3 أيام', '4 days ago': 'منذ 4 أيام', '1 week ago': 'منذ أسبوع', 'This month': 'هذا الشهر'
  };
  const arabic = localStorage.getItem('oud-lang') === 'ar';
  const switcher = document.createElement('div'); switcher.className = 'portal-language'; switcher.innerHTML = '<button data-portal-lang="en">English</button><button data-portal-lang="ar">العربية</button>';
  const topbar = document.querySelector('.topbar'); const existingTitle = topbar?.querySelector('.topbar-title'); if (existingTitle) existingTitle.remove(); const existingSignout = topbar?.querySelector('.button-secondary'); let actions = document.querySelector('.topbar-actions'); if (topbar && !actions) { actions = document.createElement('div'); actions.className = 'topbar-actions'; topbar.append(actions); if (existingSignout) actions.append(existingSignout); } if (actions) { const profile = document.createElement('div'); profile.className = 'portal-profile'; profile.innerHTML = '<strong>Ahmed Al Oud</strong><span>Hospitality Management · employee@oud.sa</span>'; actions.prepend(profile, switcher); }
  if (document.title.includes('Oud Academy')) document.querySelectorAll('.module-card').forEach((card, index) => { const thumb = document.createElement('div'); thumb.className = 'video-thumb'; thumb.innerHTML = '<img src="assets/training-thumbnail.png" alt=""><span class="thumb-play">▶</span><span class="video-duration">' + (index === 0 ? '12:40' : index === 1 ? '08:25' : '05:10') + '</span>'; card.prepend(thumb); const badge = document.createElement('span'); badge.className = 'video-badge'; badge.innerHTML = '<span class="video-play">▶</span> Video · ' + (index === 0 ? '12:40' : index === 1 ? '08:25' : '05:10'); card.insertBefore(badge, card.children[1]); });
  function apply(language) {
    localStorage.setItem('oud-lang', language); document.documentElement.lang = language; document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr'; document.body.classList.toggle('rtl', language === 'ar');
    document.querySelectorAll('[data-portal-lang]').forEach((button) => button.classList.toggle('active', button.dataset.portalLang === language));
    document.querySelectorAll('body *:not(script):not(style)').forEach((element) => { if (element.children.length) return; const original = element.dataset.originalText || element.textContent.trim(); if (!original) return; element.dataset.originalText = original; element.textContent = language === 'ar' ? (translations[original] || original) : original; });
  }
  switcher.querySelectorAll('button').forEach((button) => button.addEventListener('click', () => { apply(button.dataset.portalLang); window.dispatchEvent(new CustomEvent('oud-language-change', { detail: button.dataset.portalLang })); }));
  apply(arabic ? 'ar' : 'en');
})();
